package syncclient

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
)

// The whole value of plan mode (`*rooted.plan`, threaded through every
// reconciler as a `*Plan`) is that the preview is generated by the SAME code
// that performs the real write — so it cannot drift from reality by
// construction. That is a design argument, not a fact, until something
// actually runs both paths against identical inputs and diffs the outcome.
// This file is that gate, for all three reconcilers.
//
// Method, per reconciler: build two byte-identical fixtures (a "plan" tree
// and an "apply" tree) via an identical real setup run on both. Mutate the
// second-round input to force a create, an overwrite AND a removal in the
// section under test. Run round two in plan mode against the plan tree,
// collecting Plan.Changes(). Run round two for real against the apply tree,
// snapshotting every managed root before and after and deriving what the
// apply actually did (create/overwrite/remove) from the diff. Assert the two
// derived sets are equal, keyed by root-relative path so the comparison is
// immune to the two fixtures living at different absolute temp-dir paths.

// snapshotFiles maps every regular file under root to its content, keyed by
// slash-normalized path relative to root. Directories are not entries (a
// mutating method's Op vocabulary — create/overwrite/remove — is about file
// content, not directory scaffolding).
func snapshotFiles(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(root, p)
		if err != nil {
			return err
		}
		b, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		out[filepath.ToSlash(rel)] = string(b)
		return nil
	})
	if err != nil {
		t.Fatalf("snapshot %s: %v", root, err)
	}
	return out
}

// snapshotDirs maps every directory under root (root itself included) to
// true, keyed by slash-normalized path relative to root. Kept separate from
// snapshotFiles because directory CREATION must never be compared — MkdirAll
// is an untracked implicit side effect of writeAtomic, never itself a
// recorded Change, so treating a newly-appeared directory as a mutation
// would manufacture a mismatch the Plan was never supposed to report.
// Directory REMOVAL, by contrast, is real: it is the only way this package
// ever deletes a directory (reconcile.go's skill-dir prune), and it IS
// recorded as a Change, so realOps needs this to see it happen for real.
func snapshotDirs(t *testing.T, root string) map[string]bool {
	t.Helper()
	out := map[string]bool{}
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(root, p)
		if err != nil {
			return err
		}
		out[filepath.ToSlash(rel)] = true
		return nil
	})
	if err != nil {
		t.Fatalf("snapshot dirs %s: %v", root, err)
	}
	return out
}

// diffSnapshots derives the Op a real apply performed on each path that
// differs between two snapshots of the SAME root, taken before and after.
func diffSnapshots(before, after map[string]string) map[string]Op {
	out := map[string]Op{}
	for rel, a := range after {
		if b, existed := before[rel]; !existed {
			out[rel] = OpCreate
		} else if b != a {
			out[rel] = OpOverwrite
		}
	}
	for rel := range before {
		if _, still := after[rel]; !still {
			out[rel] = OpRemove
		}
	}
	return out
}

// labeledRoots names every boundary directory a reconciler call writes
// under (claudeDir, plus one entry per project for seeds/rules). A Change's
// Path is always absolute, under whichever temp dir a given fixture happens
// to use — so a raw path can never be compared across the plan fixture and
// the apply fixture. Reducing every path to "<label>/<root-relative path>"
// makes the two trees comparable despite living at unrelated absolute paths.
type labeledRoots map[string]string

// label finds which named root abs falls under and returns "<name>/<rel>",
// slash-normalized. Fails the test loudly if abs matches no known root —
// silently dropping an unrecognized path would hide exactly the kind of
// disagreement this gate exists to catch.
func (lr labeledRoots) label(t *testing.T, abs string) string {
	t.Helper()
	for name, root := range lr {
		rel, err := filepath.Rel(root, abs)
		if err != nil {
			continue
		}
		if rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
			continue
		}
		return name + "/" + filepath.ToSlash(rel)
	}
	t.Fatalf("path %q is not under any known root %+v", abs, lr)
	return ""
}

// planOps converts a Plan's recorded changes into a labeled-key -> Op set.
// A duplicate key (the same path recorded twice) fails the test outright
// rather than silently collapsing into one map entry, which would hide a
// real double-record defect from the comparison.
func planOps(t *testing.T, changes []Change, roots labeledRoots) map[string]Op {
	t.Helper()
	out := map[string]Op{}
	for _, c := range changes {
		key := roots.label(t, c.Path)
		if prev, dup := out[key]; dup {
			t.Fatalf("plan recorded %q twice (%v then %v)", key, prev, c.Op)
		}
		out[key] = c.Op
	}
	return out
}

// treeDigestAll returns treeDigest (see reconcile_test.go) for every labeled
// root, keyed by label — used only for the cross-fixture "setup runs
// diverged" content checks, which must stay insensitive to mtime (see
// treeDigest's doc comment). The plan-mode writes-nothing checks below use
// treeSnapshotAll/assertAllTreesUnchanged instead.
func treeDigestAll(t *testing.T, roots labeledRoots) map[string]string {
	t.Helper()
	out := make(map[string]string, len(roots))
	for name, root := range roots {
		out[name] = treeDigest(t, root)
	}
	return out
}

// treeSnapshotAll returns treeSnapshot (see reconcile_test.go) for every
// labeled root, keyed by label.
func treeSnapshotAll(t *testing.T, roots labeledRoots) map[string]map[string]entrySnapshot {
	t.Helper()
	out := make(map[string]map[string]entrySnapshot, len(roots))
	for name, root := range roots {
		out[name] = treeSnapshot(t, root)
	}
	return out
}

// assertAllTreesUnchanged is treeSnapshotAll's writes-nothing gate: it
// re-snapshots every labeled root and reports, per root, exactly which path
// and property moved — via assertTreeUnchanged — rather than only that some
// map of digests no longer matches.
func assertAllTreesUnchanged(t *testing.T, roots labeledRoots, before map[string]map[string]entrySnapshot) {
	t.Helper()
	for name, root := range roots {
		assertTreeUnchanged(t, name+" ("+root+")", root, before[name])
	}
}

// realOps snapshots every labeled root, runs apply, re-snapshots, and
// returns the labeled-key -> Op set the real writes actually produced.
func realOps(t *testing.T, roots labeledRoots, apply func()) map[string]Op {
	t.Helper()
	beforeFiles := make(map[string]map[string]string, len(roots))
	beforeDirs := make(map[string]map[string]bool, len(roots))
	for name, root := range roots {
		beforeFiles[name] = snapshotFiles(t, root)
		beforeDirs[name] = snapshotDirs(t, root)
	}
	apply()
	out := map[string]Op{}
	for name, root := range roots {
		for rel, op := range diffSnapshots(beforeFiles[name], snapshotFiles(t, root)) {
			out[name+"/"+rel] = op
		}
		// A directory present before and gone after is the skill-dir-prune
		// branch's doing (see snapshotDirs for why creation is deliberately
		// not compared here).
		afterDirs := snapshotDirs(t, root)
		for rel := range beforeDirs[name] {
			if !afterDirs[rel] {
				out[name+"/"+rel] = OpRemove
			}
		}
	}
	return out
}

// assertPlanMatchesApply is the gate's core assertion: the plan-recorded set
// and the apply-derived set must be EQUAL, not merely equal in size (a count
// match would pass if, say, the manifest were recorded twice and an artifact
// not at all). On mismatch it prints every differing (and every agreeing, for
// context) path with both sides' Op side by side — a reader can see exactly
// which path disagreed and how without re-running anything.
func assertPlanMatchesApply(t *testing.T, planned, applied map[string]Op) {
	t.Helper()
	if reflect.DeepEqual(planned, applied) {
		return
	}
	keys := map[string]bool{}
	for k := range planned {
		keys[k] = true
	}
	for k := range applied {
		keys[k] = true
	}
	sorted := make([]string, 0, len(keys))
	for k := range keys {
		sorted = append(sorted, k)
	}
	sort.Strings(sorted)

	var b strings.Builder
	b.WriteString("plan and apply disagree on what changed:\n")
	for _, k := range sorted {
		p, pOK := planned[k]
		a, aOK := applied[k]
		switch {
		case pOK && aOK && p == a:
			fmt.Fprintf(&b, "  %-55s plan=%-10s apply=%-10s\n", k, p, a)
		case pOK && aOK:
			fmt.Fprintf(&b, "  %-55s plan=%-10s apply=%-10s  <-- MISMATCHED OP\n", k, p, a)
		case pOK:
			fmt.Fprintf(&b, "  %-55s plan=%-10s apply=%-10s  <-- PLANNED BUT NOT APPLIED\n", k, p, "(absent)")
		default:
			fmt.Fprintf(&b, "  %-55s plan=%-10s apply=%-10s  <-- APPLIED BUT NOT PLANNED\n", k, "(absent)", a)
		}
	}
	t.Fatalf("%s", b.String())
}

// TestPlanMatchesApply_Reconcile is the artifacts (skill/subagent) gate: one
// unchanged artifact, one whose content changes, one newly added, one
// subagent dropped from the entitlement set (a flat file — never enters the
// skill-directory-prune branch), and two SKILLS dropped from the entitlement
// set that exercise that branch on both sides of its decision — "emptied"'s
// directory holds nothing else once SKILL.md is gone and must be pruned;
// "guarded"'s directory holds an untracked file and must NOT be pruned —
// covering unchanged/create/overwrite/remove (file AND directory) in a
// single run, against a single root (claudeDir).
func TestPlanMatchesApply_Reconcile(t *testing.T) {
	dirPlan, dirApply := t.TempDir(), t.TempDir()

	round1 := []Artifact{
		{Type: "skill", Name: "unchanged", Content: "U1"},
		{Type: "skill", Name: "changed", Content: "C1"},
		{Type: "subagent", Name: "dropped", Content: "D1"},
		{Type: "skill", Name: "emptied", Content: "E1"},
		{Type: "skill", Name: "guarded", Content: "G1"},
		// "gone" covers B2: manifest-listed but the operator deletes it by
		// hand between syncs. A real root.Remove then returns ENOENT and
		// reconcile.go's removal loop does NOT count it as removed — plan
		// mode must agree, not name a deletion the apply will not perform.
		{Type: "subagent", Name: "gone", Content: "V1"},
	}
	for _, dir := range []string{dirPlan, dirApply} {
		if _, err := Reconcile(dir, round1, nil); err != nil {
			t.Fatalf("setup Reconcile(%s): %v", dir, err)
		}
		// "guarded"'s directory gets a file the reconciler doesn't manage,
		// created directly here (not via an artifact) — precisely why it
		// must survive once SKILL.md is removed next round.
		guardFile := filepath.Join(dir, "skills", "guarded", "notes.txt")
		if err := os.WriteFile(guardFile, []byte("hand-authored"), 0o644); err != nil {
			t.Fatalf("setup untracked sibling file in %s: %v", dir, err)
		}
		// Simulate the operator deleting "gone" by hand: the manifest still
		// lists agents/gone.md as managed, but nothing is there anymore by
		// the time round 2 runs.
		goneFile := filepath.Join(dir, "agents", "gone.md")
		if err := os.Remove(goneFile); err != nil {
			t.Fatalf("setup: hand-delete %s: %v", goneFile, err)
		}
	}
	// Reconcile's manifest stores only RELATIVE paths (see reconcile.go's
	// manifest.Files), so unlike the seed/rules manifests below, nothing here
	// embeds a fixture's absolute temp-dir path — a straight digest comparison
	// is valid.
	if treeDigest(t, dirPlan) != treeDigest(t, dirApply) {
		t.Fatal("setup runs diverged; fixtures are not identical")
	}

	round2 := []Artifact{
		{Type: "skill", Name: "unchanged", Content: "U1"}, // stays identical
		{Type: "skill", Name: "changed", Content: "C2"},   // overwrite
		{Type: "subagent", Name: "new", Content: "N1"},    // create
		// "dropped" absent this round -> remove (flat file, no dir prune)
		// "emptied" absent this round -> remove; its directory ends up
		// holding nothing else, so a real run prunes it too
		// "guarded" absent this round -> remove; its directory still holds
		// notes.txt, so a real run's rmdir fails ENOTEMPTY and it survives
	}
	roots := labeledRoots{"root": dirPlan}

	before := treeSnapshot(t, dirPlan)
	var p Plan
	if _, err := Reconcile(dirPlan, round2, &p); err != nil {
		t.Fatalf("plan run: %v", err)
	}
	assertTreeUnchanged(t, dirPlan, dirPlan, before)
	planned := planOps(t, p.Changes(), roots)

	applied := realOps(t, labeledRoots{"root": dirApply}, func() {
		if _, err := Reconcile(dirApply, round2, nil); err != nil {
			t.Fatalf("apply run: %v", err)
		}
	})

	assertPlanMatchesApply(t, planned, applied)
}

// TestPlanMatchesApply_ReconcileSeeds is the seeds gate — the section the
// task exists chiefly to cover. seed.go's write pass (seed.go ~line 272)
// writeAtomic's a target, and the strip pass (seed.go ~line 527, via
// stripUndesired) can re-read that SAME path later in the SAME call: in
// real mode the second read sees the just-written bytes, in plan mode it
// sees pre-run bytes (the write was only recorded, never applied). "keep"
// below is exactly that case — a project that stays entitled AND changes
// body, so its target is written in the write pass and revisited (via the
// ledger) in the strip pass within the same ReconcileSeeds call.
func TestPlanMatchesApply_ReconcileSeeds(t *testing.T) {
	type fixture struct{ home, keep, drop, nw string }
	newFixture := func() fixture {
		return fixture{home: t.TempDir(), keep: t.TempDir(), drop: t.TempDir(), nw: t.TempDir()}
	}
	planFx, applyFx := newFixture(), newFixture()

	round1 := []Artifact{
		// project scope: entitled to keep+drop this round; gains a create at
		// "nw" and a body change at "keep" next round; "drop" is de-registered
		// next round, so its previously-written block gets stripped.
		{Name: "alpha", Type: "subagent", MemoryScope: "project", MemorySeed: "BODY-A1"},
		// user scope, stable body across both rounds: proves an unchanged
		// target is recorded on NEITHER side.
		{Name: "beta", Type: "subagent", MemoryScope: "user", MemorySeed: "BODY-B-STABLE"},
	}
	for _, fx := range []fixture{planFx, applyFx} {
		if _, err := ReconcileSeeds(fx.home, []string{fx.keep, fx.drop}, round1, nil); err != nil {
			t.Fatalf("setup ReconcileSeeds: %v", err)
		}
	}
	// "home" is deliberately excluded from this parity check: its manifest
	// (.orbeat-sync-manifest.json) embeds each project's ABSOLUTE path in the
	// Seeds ledger, and planFx/applyFx's project temp dirs are never at the
	// same absolute path — so the manifest bytes legitimately differ between
	// the two fixtures even when the run behaved identically. "keep"/"drop"
	// carry only rendered seed-block content (name+hash+body), which is
	// path-independent, so they ARE valid to compare directly.
	if treeDigest(t, planFx.keep) != treeDigest(t, applyFx.keep) ||
		treeDigest(t, planFx.drop) != treeDigest(t, applyFx.drop) {
		t.Fatal("setup runs diverged; fixtures are not identical")
	}

	round2 := []Artifact{
		{Name: "alpha", Type: "subagent", MemoryScope: "project", MemorySeed: "BODY-A2"},
		{Name: "beta", Type: "subagent", MemoryScope: "user", MemorySeed: "BODY-B-STABLE"},
	}
	rootsFor := func(fx fixture) labeledRoots {
		return labeledRoots{"home": fx.home, "keep": fx.keep, "drop": fx.drop, "new": fx.nw}
	}

	before := treeSnapshotAll(t, rootsFor(planFx))
	var p Plan
	if _, err := ReconcileSeeds(planFx.home, []string{planFx.keep, planFx.nw}, round2, &p); err != nil {
		t.Fatalf("plan run: %v", err)
	}
	assertAllTreesUnchanged(t, rootsFor(planFx), before)
	planned := planOps(t, p.Changes(), rootsFor(planFx))

	applied := realOps(t, rootsFor(applyFx), func() {
		if _, err := ReconcileSeeds(applyFx.home, []string{applyFx.keep, applyFx.nw}, round2, nil); err != nil {
			t.Fatalf("apply run: %v", err)
		}
	})

	assertPlanMatchesApply(t, planned, applied)
}

// TestPlanMatchesApply_ReconcileRules mirrors the seeds gate for rules: one
// project stays entitled and its rule body changes (AGENTS.md overwrite;
// CLAUDE.md's @AGENTS.md import is already present from round 1 and must NOT
// appear on either side), one project is newly registered (create, both
// files), and one is de-registered (its previously-written blocks stripped
// from both files — an in-place overwrite, since neither managed file is
// ever deleted).
func TestPlanMatchesApply_ReconcileRules(t *testing.T) {
	type fixture struct{ home, keep, drop, nw string }
	newFixture := func() fixture {
		return fixture{home: t.TempDir(), keep: t.TempDir(), drop: t.TempDir(), nw: t.TempDir()}
	}
	planFx, applyFx := newFixture(), newFixture()

	round1 := []Artifact{{Name: "std", Type: "rule", Content: "RULE-1"}}
	for _, fx := range []fixture{planFx, applyFx} {
		if _, err := ReconcileRules(fx.home, []string{fx.keep, fx.drop}, round1, nil); err != nil {
			t.Fatalf("setup ReconcileRules: %v", err)
		}
	}
	// Same "home" exclusion as the seeds test: the Rules ledger stores each
	// project's absolute path, which legitimately differs between the two
	// fixtures' temp dirs. AGENTS.md/CLAUDE.md content is path-independent.
	if treeDigest(t, planFx.keep) != treeDigest(t, applyFx.keep) ||
		treeDigest(t, planFx.drop) != treeDigest(t, applyFx.drop) {
		t.Fatal("setup runs diverged; fixtures are not identical")
	}

	round2 := []Artifact{{Name: "std", Type: "rule", Content: "RULE-2"}}
	rootsFor := func(fx fixture) labeledRoots {
		return labeledRoots{"home": fx.home, "keep": fx.keep, "drop": fx.drop, "new": fx.nw}
	}

	before := treeSnapshotAll(t, rootsFor(planFx))
	var p Plan
	if _, err := ReconcileRules(planFx.home, []string{planFx.keep, planFx.nw}, round2, &p); err != nil {
		t.Fatalf("plan run: %v", err)
	}
	assertAllTreesUnchanged(t, rootsFor(planFx), before)
	planned := planOps(t, p.Changes(), rootsFor(planFx))

	applied := realOps(t, rootsFor(applyFx), func() {
		if _, err := ReconcileRules(applyFx.home, []string{applyFx.keep, applyFx.nw}, round2, nil); err != nil {
			t.Fatalf("apply run: %v", err)
		}
	})

	assertPlanMatchesApply(t, planned, applied)
}

// TestPlanMatchesApply_ReconcileAbsentSyncRoot is §7 gate 2's absent-root
// case (B1): a plan computed against a sync root that has never existed must
// name exactly what a real first-ever sync creates. It can't reuse
// labeledRoots/realOps/planOps: snapshotFiles and treeDigest both walk the
// root, which requires it to already exist — and the entire point of this
// fixture is that it does not — so the comparison is done directly: collect
// the plan's recorded creates, run a real sync against an equally-fresh
// root, and assert the two path sets are identical.
func TestPlanMatchesApply_ReconcileAbsentSyncRoot(t *testing.T) {
	dirPlan := filepath.Join(t.TempDir(), "never-synced")
	dirApply := filepath.Join(t.TempDir(), "never-synced")

	arts := []Artifact{
		{Type: "skill", Name: "s1", Content: "S1"},
		{Type: "subagent", Name: "a1", Content: "A1"},
	}

	var p Plan
	if _, err := Reconcile(dirPlan, arts, &p); err != nil {
		t.Fatalf("plan run: %v", err)
	}
	if _, err := os.Stat(dirPlan); !os.IsNotExist(err) {
		t.Fatalf("plan mode must not create the sync root, stat err=%v", err)
	}

	if _, err := Reconcile(dirApply, arts, nil); err != nil {
		t.Fatalf("apply run: %v", err)
	}

	assertPlannedCreatesMatchApplyFiles(t, dirPlan, p.Changes(), dirApply)
}

// TestPlanMatchesApply_ReconcileSeedsAbsentSyncRoot mirrors the above for
// seeds (B1), for a user-scope target — the boundary the fix actually
// touches (project-scope targets were never broken by B1; see
// TestReconcileSeedsPlanModeAgainstAbsentRoot).
func TestPlanMatchesApply_ReconcileSeedsAbsentSyncRoot(t *testing.T) {
	homePlan := filepath.Join(t.TempDir(), "never-synced")
	homeApply := filepath.Join(t.TempDir(), "never-synced")
	arts := []Artifact{{Name: "alpha", Type: "subagent", Content: "A", MemoryScope: "user", MemorySeed: "USER-BODY"}}

	var p Plan
	if _, err := ReconcileSeeds(homePlan, nil, arts, &p); err != nil {
		t.Fatalf("plan run: %v", err)
	}
	if _, err := os.Stat(homePlan); !os.IsNotExist(err) {
		t.Fatalf("plan mode must not create the sync root, stat err=%v", err)
	}

	if _, err := ReconcileSeeds(homeApply, nil, arts, nil); err != nil {
		t.Fatalf("apply run: %v", err)
	}

	assertPlannedCreatesMatchApplyFiles(t, homePlan, p.Changes(), homeApply)
}

// assertPlannedCreatesMatchApplyFiles is the absent-root gate's shared
// assertion: every recorded Change must be a create naming a path (relative
// to planRoot) that the real run produced under applyRoot, and every file
// the real run produced must have a matching planned create — a two-sided
// check, not just a count, so a duplicate-recorded or silently-dropped
// change would fail this even if the totals happened to match.
func assertPlannedCreatesMatchApplyFiles(t *testing.T, planRoot string, changes []Change, applyRoot string) {
	t.Helper()
	applyFiles := snapshotFiles(t, applyRoot)
	planned := map[string]bool{}
	for _, c := range changes {
		if c.Op != OpCreate {
			t.Fatalf("change %+v: want op=create against a never-synced root", c)
		}
		rel, err := filepath.Rel(planRoot, c.Path)
		if err != nil {
			t.Fatalf("change path %q not under the plan root: %v", c.Path, err)
		}
		planned[filepath.ToSlash(rel)] = true
	}
	if len(planned) != len(applyFiles) {
		t.Fatalf("plan recorded %d changes, apply produced %d files: planned=%v applied=%v",
			len(planned), len(applyFiles), planned, applyFiles)
	}
	for rel := range applyFiles {
		if !planned[rel] {
			t.Fatalf("apply created %q which the plan never named", rel)
		}
	}
}
